language: python

python:
  - 2.7

service:
  - postgresql

addons:
  postgresql: 9.5
  apt:
    packages:
      - postgresql-9.5-postgis-2.3
      - postgresql-9.5-postgis-scripts
  
before_install:
  - export PYTHONPATH=$HOME/builds/audaciouscode/Web-Historian-Server
  
install:
  - pip install -r requirements.txt

before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c "create extension postgis"
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - psql -U postgres -c "CREATE EXTENSION postgis" -d travisci
  - psql -U postgres -c "CREATE EXTENSION postgis_topology" -d travisci

script:
#  - git clone https://github.com/audaciouscode/PassiveDataKit-Django.git
#  - mv PassiveDataKit-Django passive_data_kit
  - pip install -r passive_data_kit/requirements.txt
  - cp historian/local_settings.travis.py historian/local_settings.py
  - python manage.py migrate
  - python manage.py test
  - pylint passive_data_kit
  - pylint web_historian
  - bandit -r .
