sudo: required

env:
  global:
    - PGPORT=5433
    - PGHOST=localhost

language: python

python:
  - 2.7

service:
  - postgresql

addons:
  apt:
    sources:
      - precise-pgdg-9.5
    packages:
      - postgresql-9.5
      - postgresql-contrib-9.5
      - postgis
      - postgresql-9.5-postgis-2.2
      - postgresql-9.5-postgis-scripts
      - libgeos-3.2.2
      - libgeos-c1
      - libproj0
      - proj-data
      - proj-bin
    
  postgresql: 9.5
  
before_install:
  - export PYTHONPATH=$HOME/builds/audaciouscode/Previsit-Django
  
install:
  - pip install -r requirements.txt

before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c "create extension postgis"
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - psql -U postgres -c "CREATE EXTENSION postgis" -d travisci
  - psql -U postgres -c "CREATE EXTENSION postgis_topology" -d travisci

script:
#  - git clone https://github.com/audaciouscode/PassiveDataKit-Django.git
#  - mv PassiveDataKit-Django passive_data_kit
  - pip install -r passive_data_kit/requirements.txt
  - cp pdk_site/local_settings.travis.py pdk_site/local_settings.py
  - python manage.py migrate
  - python manage.py test
  - pylint passive_data_kit
  - pylint web_historian
  - bandit -r .
