# pylint: skip-file
# Generated by Django 3.2.18 on 2023-04-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_historian', '0006_auto_20170922_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providedidentifier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='urlaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='urlcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
